#:kivy 2.0.0

<CollectLogIn@MDBoxLayout>:
    orientation:"vertical"
    
    MDTextField:
        hint_text: "Paciente"
        required: True
        size_hint: 1, 1
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
        
    MDTextField:
        hint_text: "ID"
        required: True
        size_hint: 1, 1
        font_size: '25sp'
        password: False
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE

    MDTextButton:
        text:"Esqueci minha senha"
        size_hint: 1, 0.5
        halign: 'right'
        font_size: app.BUTTON_FONT

    MDFillRoundFlatIconButton:
        text:"Entrar"
        icon:"login"
        size_hint: 1, 0.4
        font_size: app.BUTTON_FONT
        on_release:
            app.root.current = "collect_screen"


<CollectPage>:
    orientation:"vertical"
    
    MDBoxLayout:
        id:main_layout
        orientation: "horizontal"
        Busca:
            id:busca
        ScrollView:
            id:resultados
            do_scroll_x: False
            do_scroll_y: True
            size_hint: 1, 1
            MDGridLayout:
                cols:1
                size_hint: 1, None
                height: self.minimum_height
                MDGridLayout:
                    padding: [0,'10dp',0,'10dp']
                    spacing: '10dp'
                    size_hint: 1, None
                    height: self.minimum_height
                    id:main_layout_resultados
                    cols:1
                
                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: self.minimum_height
                    id: nav_buttons
                    MDTextButton:
                        text: "1"
                        id: go_to_first
                        on_release: root.on_go_to_first()

                    MDIconButton:
                        icon:"arrow-left"
                        id: go_to_previous
                        on_release: root.on_go_to_previous()
                    
                    MDLabel:
                        text:str(root.current_page)
                        id: current_page
                        size_hint_x: 1
                    
                    MDIconButton:
                        icon:"arrow-right"
                        id: go_to_next
                        on_release: root.on_go_to_next()
                    
                    MDTextButton:
                        text: "1"
                        id: go_to_last
                        on_release: root.on_go_to_last()

    MDBoxLayout:
        id:buttons_layout
        orientation: "horizontal"
        size_hint_y: 0.1
        Button:
            id:submit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: app.TEXT_SIZE
            text:"Submit"
            on_release: root.on_submit()
            
        Button:
            id:collect_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: app.TEXT_SIZE
            on_release: root.collect_release()
            text:"Collect"
        
        Button:
            id:exit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: app.TEXT_SIZE
            on_release: app.root.current = "main_screen"
            text:"Sair"
            
    

<Resultados>:
    do_scroll_x: False
    do_scroll_y: True
    size_hint: 1, 1
    MDBoxLayout:
        orientation: "vertical"
        MDGridLayout:
            padding: [0,'10dp',0,'10dp']
            spacing: '10dp'
            size_hint: 1, None
            height: self.minimum_height
            id:main_layout_resultados
            cols:1
        
        MDBoxLayout:
            orientation: "horizontal"
            size_hint: 1, None
            height: self.minimum_height
            id: nav_buttons
            MDTextButton:
                text: "1"
                #on_release: root.on_go_to_first()

            MDIconButton:
                icon:"arrow-left"
                #on_release: root.on_go_to_previous()
            
            MDLabel:
                text:"1"
                size_hint_x: 1
            
            MDIconButton:
                icon:"arrow-right"
                #on_release: root.on_go_to_next()
            
            MDTextButton:
                text: "1"
                #on_release: root.on_go_to_last()


    

