#:kivy 2.0.0

<SearchEditPage>:
    orientation:"vertical"
    
    MDBoxLayout:
        id:main_layout
        orientation: "horizontal"
        Busca:
            id:busca
        Resultados:
            id:resultados

    MDBoxLayout:
        id:buttons_layout
        orientation: "horizontal"
        size_hint_y: 0.1
        Button:
            id:submit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: '25sp'
            text:"Submit"
            on_release: root.on_submit()
            
        Button:
            id:edit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: '25sp'
            on_press: root.edit_press()
            on_release:
                root.edit_release()
                app.root.current = "edit_screen"
            text:"Editar"

<EditPage>:
    cols:2
    MDTextField:
        id: nome
        size_hint_y: 1
        hint_text: "Nome"
        required: True
        on_text_validate: root.nome = self.text
        text: root.nome
    
    MDTextField:
        id: id
        size_hint_y: 1
        hint_text: "ID"
        required: True
        on_text_validate: root.id = self.text
    
    MDTextField:
        id: dose
        size_hint_y: 1
        hint_text: "Dosagem"
        required: True
        on_text_validate: root.dose = self.text
    
    MDTextField:
        id: apresentacao
        size_hint_y: 1
        hint_text: "apresentacao"
        required: True
        on_text_validate: root.apresentacao = self.text

    MDTextField:
        id: position
        size_hint_y: 1
        hint_text: "Posição"
        required: True
        max_text_length: 5
        on_text_validate: root.position = self.text
    
    MDBoxLayout:
        orientation: "vertical"
        MDLabel:
            text:"Imagem"
            size_hint: 1, 0.3
        
        MDBoxLayout:
            orientation: "horizontal"
            Image:
                id: imagem_remedio
                source: root.photo_path
                size_hint_x: 2
            MDBoxLayout:
                orientation: "vertical"
                MDRoundFlatIconButton:
                    icon: root.photo_icon
                    text: "Mudar Foto"
                    on_release:
                        app.root.current = "camera_screen"


                MDRoundFlatIconButton:
                    icon: root.register_icon
                    text: "Registrar"
                    on_press:
                        root.submit_item()
                        app.root.current = "main_screen"
