#:kivy 2.0.0

<SearchEditPage>:
    orientation:"vertical"
    
    MDBoxLayout:
        id:main_layout
        orientation: "horizontal"
        Busca:
            id:busca
        ScrollView:
            id:resultados
            do_scroll_x: False
            do_scroll_y: True
            size_hint: 1, 1
            MDGridLayout:
                cols:1
                size_hint: 1, None
                height: self.minimum_height
                MDGridLayout:
                    padding: [0,'10dp',0,'10dp']
                    spacing: '10dp'
                    size_hint: 1, None
                    height: self.minimum_height
                    id:main_layout_resultados
                    cols:1
                
                MDBoxLayout:
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: self.minimum_height
                    id: nav_buttons
                    MDTextButton:
                        text: "1"
                        id: go_to_first
                        on_release: root.on_go_to_first()

                    MDIconButton:
                        icon:"arrow-left"
                        id: go_to_previous
                        on_release: root.on_go_to_previous()
                    
                    MDLabel:
                        text:str(root.current_page)
                        id: current_page
                        size_hint_x: 1
                    
                    MDIconButton:
                        icon:"arrow-right"
                        id: go_to_next
                        on_release: root.on_go_to_next()
                    
                    MDTextButton:
                        text: "1"
                        id: go_to_last
                        on_release: root.on_go_to_last()

    MDBoxLayout:
        id:buttons_layout
        orientation: "horizontal"
        size_hint_y: 0.1
        Button:
            id:submit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: app.BUTTON_FONT
            text:"Submit"
            on_release: root.on_submit()
            
        Button:
            id:edit_button
            background_normal: ''
            background_color:252.0/256, 83.0/256, 94.0/256, 1
            size_hint_x:1
            font_size: app.BUTTON_FONT
            on_press: root.edit_press()
            on_release:
                root.edit_release()
                app.root.current = "edit_screen"
            text:"Editar"

<EditPage>:
    cols:2
    MDTextField:
        id: nome
        size_hint_y: 1
        hint_text: "Nome"
        required: True
        on_text_validate: root.nome = self.text
        text: root.nome
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: id
        size_hint_y: 1
        hint_text: "ID"
        required: True
        on_text_validate: root.id = self.text
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: dose
        size_hint_y: 1
        hint_text: "Dosagem"
        required: True
        on_text_validate: root.dose = self.text
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: apresentacao
        size_hint_y: 1
        hint_text: "apresentacao"
        required: True
        on_text_validate: root.apresentacao = self.text
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE

    MDTextField:
        id: position
        size_hint_y: 1
        hint_text: "Posição"
        required: True
        max_text_length: 5
        on_text_validate: root.position = self.text
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDRoundFlatIconButton:
        icon: root.register_icon
        text: "Registrar"
        font_size: app.BUTTON_FONT
        on_press:
            root.submit_item()
            app.root.current = "main_screen"
        
        #MDBoxLayout:
        #    orientation: "horizontal"
            #Image:
            #    id: imagem_remedio
            #    source: root.photo_path
            #    size_hint_x: 2
        #    MDBoxLayout:
        #        orientation: "vertical"
        #        MDRoundFlatIconButton:
        #            icon: root.photo_icon
        #            text: "Mudar Foto"
        #            font_size: app.BUTTON_FONT
        #            on_release:
        #                app.root.current = "camera_screen"


        #        MDRoundFlatIconButton:
        #            icon: root.register_icon
        #            text: "Registrar"
        #            font_size: app.BUTTON_FONT
        #            on_press:
        #                root.submit_item()
        #                app.root.current = "main_screen"


