#:kivy 2.0.0

<LogInPage>:
    orientation: "vertical"
    MDBottomNavigation:
        #color stuff
        #panel_color: 0, 0, 1, .8
        MDBottomNavigationItem:
            name: "login"
            text: "Log-In"
            icon:'login'
            active_font_size: app.BUTTON_FONT
            inactive_font_size: app.BUTTON_FONT
            FloatLayout:

                ActualLogIn:
                    size_hint:0.5, 0.6
                    pos_hint: {'center_x':.5, 'center_y': .5}

        MDBottomNavigationItem:
            name: "help"
            text: "Ajuda"
            icon:'help'
            active_font_size: app.BUTTON_FONT
            inactive_font_size: app.BUTTON_FONT
            HelpPage:



<ActualLogIn>:
    orientation:"vertical"
    
    MDTextField:
        id: user
        hint_text: "Usuário"
        required: True
        size_hint: 1, 1
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
        
    MDTextField:
        hint_text: "Senha"
        required: True
        size_hint: 1, 1
        font_size: '25sp'
        password: True
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE

    MDTextButton:
        text:"Esqueci minha senha"
        size_hint: 1, 0.5
        halign: 'right'
        font_size: app.BUTTON_FONT

    MDFillRoundFlatIconButton:
        text:"Entrar"
        icon:"login"
        size_hint: 1, 0.4
        font_size: app.BUTTON_FONT
        on_release:
            root.on_login()
            #app.root.current = "main_screen"

<HelpPage@MDBoxLayout>:
    MDLabel:
        text: "Texto da página de ajuda"
        font_size: app.TEXT_SIZE
