#:kivy 2.0.0

<WindowManager>:
    LogInScreen:
    MainScreen:
    AdminMainScreen:
    EditScreen:
    CollectScreen:


<MainScreen>:
    name: "main_screen"
    on_leave: app.previous_screen = self.name
    on_enter: app.current_screen = self.name
    MainPage:
        id: main_page

<AdminMainScreen>:
    name: "admin_main_screen"
    on_leave: app.previous_screen = self.name
    on_enter: app.current_screen = self.name
    AdminMainPage:
        id: admin_main_page

<LogInScreen>:
    name: "log_in_screen"
    on_leave: app.previous_screen = self.name
    on_enter: app.current_screen = self.name
    LogInPage:
        id:log_in_main_page


<EditScreen>:
    on_leave: app.previous_screen = self.name
    on_enter: app.current_screen = self.name
    name: "edit_screen"
    EditPage:
        id: edit_page

<CollectScreen>:
    on_leave: app.previous_screen = self.name
    on_enter: app.current_screen = self.name
    name: "collect_screen"
    CollectPage:
        id: collect_page