#:kivy 2.0.0

<Busca>:
    orientation:"vertical"
    MDTextField:
        id: nome
        size_hint_y: 1
        hint_text: "Nome"
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: id
        size_hint_y: 1
        hint_text: "ID"
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: dose
        size_hint_y: 1
        hint_text: "Dosagem"
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
    
    MDTextField:
        id: apresentacao
        size_hint_y: 1
        hint_text: "apresentacao"
        font_size: app.TEXT_FILL_SIZE
        hint_font_size: app.TEXT_SIZE
